Class DigitalOceanDroplet
{
    [int]$Id
    [string]$Name
    [int]$Memory
    [int]$VCPUs
    [int]$DiskSize
    [bool]$Locked
    [datetime]$CreatedAt
    [string]$Status
    [int[]]$BackupIds
    [int[]]$SnapshotIds
    [object[]]$Features
    [object]$Region
    [object]$Image
    [object]$Size
    [string]$SizeSlug
    [object]$Networks
    [object]$Kernel
    [object]$NextUpdateWindow
    [string[]]$Tags
    [int[]]$VolumeIds
}